### ISSUE TITLE
Option to keep whitelist as-is

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#119]
Basically a toggle for #43 because some users/modpacks may prefer that. 

I tried to investigate that code to make a PR but didn't really understand where you actually remove a server from whitelist upon successful check, so I gave up for now.

**Comment by Aizistral** [comment]
They are never removed from whitelist. Server safety status is updated after successful login, with respect to data gathered during login process: https://github.com/Aizistral-Studios/No-Chat-Reports/blob/1.19.1-Fabric-Port/src/main/java/com/aizistral/nochatreports/NoChatReportsClient.java#L101-L105

**Comment by Aizistral** [comment]
Whitelisting a server basically makes it so that mod skips the step with warning screen and operates as if user clicked "Proceed". If there is no warning screen (i.e. server doesn't have `enforce-secure-profile` enabled) - it doesn't do anything. Server will remain in the whitelist, but it will only matter if it's configuration changes in the future.
