### ISSUE TITLE
Allowing the multiplayer button when banned

### ISSUE THREAD

**Issue by thepwrtank18** [Aizistral-Studios/No-Chat-Reports#26]
This would let banned players servers with `online-mode=false`. You won't be able to access servers that have `online-mode=true`, but at least you can play with your friends.

The Realms button would stay grayed out, since it wouldn't work properly anyway.

**Comment by Aizistral** [comment]
This is already implemented in https://github.com/Aizistral-Studios/No-Chat-Reports/commit/a76167b7c8b303bf019a3b1493ea54cf2473c667, I just need to actually release for 1.19.1, which is yet to drop.

**Comment by coyotesfrontier** [comment]
Could this be augmented to allow accounts that are unable to play multiplayer due to having the age set too young? I have a spare account that I bought for my brother, who is currently 11. I made the mistake of listing his real age in the account creation process, which caused the account to be unable to play multiplayer in post-1.18 versions. I ended up buying him a second account with a false age so he could play multiplayer with me, but I still have the original account lying around.

**Comment by thepwrtank18** [comment]
This. I've been told to get lost by Microsoft when spending my own money because my account is restricted.

**Comment by Aizistral** [comment]
> Could this be augmented to allow accounts that are unable to play multiplayer due to having the age set too young?

Why not.

**Comment by Madis0** [comment]
I'd appreciate some options for both, as I don't really want to condone offline mode server usage or ban circumvention overall in my modpack.

Edit: I saw that there is one option, does it work identically for both cases?

**Comment by Aizistral** [comment]
> Edit: I saw that there is one option, does it work identically for both cases?

Yes. Why would that not be enough?

**Comment by Madis0** [comment]
Oh, then indeed one option is fine. I thought underage players could've still joined online-mode servers with a workaround.

**Comment by Aizistral** [comment]
Was added in 1.19.1-pre2-v1.3.0.
