### ISSUE TITLE
Replace the signature message

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#261]
### Idea

In 1.19.3, NCR detects the signature requirement by
> chat.disabled.missingProfileKey
> Chat disabled due to missing profile public key. Please try reconnecting.

That message should be hidden as it doesn't really give much info to the user.

### Reasoning

- User gets confused by the wording of the message
- User does not actually need to reconnect
- User can already see the NCR chat status
- The message becomes wrong as soon as the user actually signs the chat

**Comment by Aizistral** [comment]
I think I'll just replace it with something more informative instead of hiding it entirely.

**Comment by Madis0** [comment]
That's a possibility, however it would still spam the chat and logs, regardless of whether the user actually decides to sign at that point... 
And when the user sends the logs to a server admin for any reason, the admin may get mad or confused about this kind of mod's presence, even if the server _does_ enforce signatures. So that would conflict #255, kind of.

**Comment by Aizistral** [comment]
> So that would conflict https://github.com/Aizistral-Studios/No-Chat-Reports/issues/255, kind of.

#255 is about a feature user has no direct control over. It's user's ability and responsibility to supervise what they send to server admins however, especially when they are known for enforcing unfavorable policies.

The reason I would prefer to keep some kind of message is because some servers might opt to replace it with something custom, in which case NCR will fail to detect it. Establishing a connection between warning message and prompt that the mod opens will give users better chance to identify this as an incompatibility and report it.

**Comment by Madis0** [comment]
> The reason I would prefer to keep some kind of message is because some servers might opt to replace it with something custom, in which case NCR will fail to detect it. Establishing a connection between warning message and prompt that the mod opens will give users better chance to identify this as an incompatibility and report it.

Well, I would say that the user could also draw the connection between a lack of an error vs an error + NCR bug. Anyway, would you consider an option to simply make that message blank (if removing would take more effort)?

**Comment by Aizistral** [comment]
> Anyway, would you consider an option to simply make that message blank (if removing would take more effort)?

Removing it wouldn't take much effort. Yeah, I can do an option.
