### ISSUE TITLE
Cannot sign messages in an offline server

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#272]
### Modloader

Fabric

### Minecraft Version

22w44a

### Modloader Version

Fabric Loader 0.14.10, bundled API

### No Chat Reports Version

22w44a-v1.14.3

### Bug Description

NCR does not properly sign the messages on an offline server, so I get this message on login
![image](https://user-images.githubusercontent.com/8611110/200073683-8a1c1fec-d732-455a-9eca-90a0d38b7d27.png)

### Steps to Reproduce

1. Join an offline server with an online ~~or offline~~ account (signing requirement in server.properties doesn't matter, it doesn't enforce either way)
2. Notice how it - of course - doesn't require signing
3. Click the chat icon to whitelist the server
4. Get kicked
5. Attempt to rejoin
6. Get kicked again
7. Disable NCR from server list and rejoin
8. It works

### Other Information

Of course signing one's messages in an offline server is pointless, but NCR still breaks here

**Comment by P3rf3ctXZer0** [comment]
If you are admin it seems to ignore this issue and let you connect I have no idea why.

**Comment by Aizistral** [comment]
So actually this is a vanilla bug lol. It happens because server assigns player a different UUID than that which their keypair is issued for. For that reason it only happens if you log into offline-mode server with an online account, and whether or not you have NCR installed is not relevant.

This needs to be fixed in vanilla, ideally in server code. I can't be bothered to report this to Mojang, but feel free to do so yourself if you feel like.

**Comment by Madis0** [comment]
The bug was fixed on vanilla 22w45a, and therefore it is irrelevant since the release of NCR 22w46a-v1.15.0.
