### ISSUE TITLE
Messages seen only by mod users

### ISSUE THREAD

**Issue by KaspianDev** [Aizistral-Studios/No-Chat-Reports#315]
### Idea

Would be nice to have a system that shows messages I send in insecure server only to other people using this mod. This can use existing encryption but with one non changing key which all clients using this mod will have and will be able to decrypt. This can also use some other form of messaging, the general idea matters to me.

Not sure if this was suggested before.

### Reasoning

While playing on insecure servers chatting exposes me to chat reporting. Which I wouldn't like to happen anymore.

**Comment by Madis0** [comment]
That would partially invalidate the point, because Mojang could just get the key that NCR uses and use that to take action on reports.
Use of an external chat server was already suggested several times, e.g. #14, #249.

**Comment by KaspianDev** [comment]
They can't really prove anything though.

+ if another from of messaging is used, messages can't be even seen by regular player

**Comment by Aizistral** [comment]
I you want to use just encryption with no external message relay involved then there's already default encryption key for that purpose, although where signing is enforced you're still signing your messages, so if encryption can be broken (which it can be in this case, since anyone can get the key) your messages can technically still serve as report evidence. The only reasonable way I see around this problem is sending messages through another service entirely without involving actual game server, which, as @Madis0 correctly pointed out, was already suggested and is currently in consideration phase. Based on that I mark this issue as duplicate.
