### ISSUE TITLE
§ is appeared in encrypted messages

### ISSUE THREAD

**Issue by IlyaTheSawmill** [Aizistral-Studios/No-Chat-Reports#350]
### Modloader

Forge

### Minecraft Version

1.19.3

### Modloader Version

Forge 44.0.48

### No Chat Reports Version

1.19.3-v1.6.0

### Bug Description

I am using Caesar to encrypt messages, and I'm kicked by the server because invaild characters. I think § is appeared in the encrypted message.

### Other Information

The server is mine, and have not any plugins except FreedomChat and AuthMe.

**Comment by Madis0** [comment]
To help debug this, what is the number you are using in Caesar and the message you sent?

**Comment by IlyaTheSawmill** [comment]
I don't remember this, but the message I sent is Chinese.

**Comment by FavoritoHJS** [comment]
I don't think every valid unicode codepoint has its immediate surrounding codepoints also be valid unicode codepoints.

and since i'm guessing the unicode caesar doesn't check to make sure the codepoints it sends are valid...

i'm not sure if there's a way to fix this without rewriting, and I'm doubtful that will be worth the effort.

**Comment by Aizistral** [comment]
I don't think it's an issue with `§` specifically because that particular symbol is checked for and replaced with another one. Unfortunately I need an exact shift and an example of message text that causes the issue in order to be able to reproduce and fix it.

**Comment by IlyaTheSawmill** [comment]
I don't think it needs to be fixed because invaild characters always appear in the Unicode table, which cannot be avoided when using Caesar encryption.
