### ISSUE TITLE
Cannot build from source on Ubuntu

### ISSUE THREAD

**Issue by spymain** [Aizistral-Studios/No-Chat-Reports#399]
### Modloader

Fabric

### Minecraft Version

1.19.4

### Modloader Version

N/A

### No Chat Reports Version

1.19.4-c2.1.3

### Bug Description

The compilation fails with:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':Forge:runtimeClasspathCopy'.
> Could not find me.shedaniel.cloth:cloth-config-forge:10.0.96_mapped_official_1.19.4.
  Searched in the following locations:
    - file:/home/joe/.gradle/caches/forge_gradle/bundled_deobf_repo/me/shedaniel/cloth/cloth-config-forge/10.0.96_mapped_official_1.19.4/cloth-config-forge-10.0.96_mapped_official_1.19.4.pom
    - file:/home/joe/.gradle/caches/forge_gradle/bundled_deobf_repo/me/shedaniel/cloth/cloth-config-forge/10.0.96_mapped_official_1.19.4/cloth-config-forge-10.0.96_mapped_official_1.19.4.jar
  Required by:
      project :Forge

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 48s
```
I am using Java 17.0.7 with openjdk.

My gradle version is 4.4.1

Searching for this bug, I have saw that others have had success by deleting the gradle caches for `forge_gradle`, though this did not work for me.

Below I have appended the output of gradle as it builds.

As a side note, I noticed the readme mentions a Discord contact existing, though I could not find it anywhere. Does it still exist?

Finally, I would like to apologize in advance for wasting your time in the event the solution to my problem turns out to be trivial.

### Steps to Reproduce

```
rm -rf ~/.gradle/caches/forge_gradle
git clone https://github.com/Aizistral-Studios/No-Chat-Reports.git
cd No-Chat-Reports/
chmod 700 gradlew
./gradlew build.gradle
```

### Other Information

[build-output.txt](https://github.com/Aizistral-Studios/No-Chat-Reports/files/11523710/build-output.txt)

**Comment by Madis0** [comment]
https://discord.gg/the-architect-s-domain-757941072449241128

The mod does not work in Intellij anymore, and is using Eclipse instead, so I believe building via Gradle is just not sufficient.

**Comment by Aizistral** [comment]
> The mod does not work in Intellij anymore, and is using Eclipse instead, so I believe building via Gradle is just not sufficient.

1. That it doesn't work for you doesn't mean it doesn't work for everyone.
2. As far as I can see they are using plain terminal commands, which should work fine.

Furthermore, I am certain that this issue is not universal as well, because we have a build on Ubuntu in build workflow here on Github, see https://github.com/Aizistral-Studios/No-Chat-Reports/blob/1.19.4-Unified/.github/workflows/build.yml

From the build output it appears that the issue is that the Gradle tries to fetch `.pom` for cloth config from `https://dvs1.progwml6.com/files/maven/me/shedaniel/cloth/cloth-config-forge/10.0.96/cloth-config-forge-10.0.96.pom`, which fails. This address is unreachable to me either, but I don't know why it would look for it in there in the first place, as it lives in a completely different repository.

**Comment by Aizistral** [comment]
Since I don't actually remember what that progwml6 repo is even for, I removed it in the latest commit fd7795b. Try to build again.

**Comment by Aizistral** [comment]
> Furthermore, I am certain that this issue is not universal as well, because we have a build on Ubuntu in build workflow here on Github

Now that I look at them, it seems that the workflow failed in two recent PRs (#398 and #400) with the same error as you got. I suspect the repository in question has only recently become defunct. Removing it from buildscript seems to have solved the problem.
