### ISSUE TITLE
Offline servers should never have "red" warnings

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#44]
From what I understand about vanilla chat behaviour (the red bars/(!)-things that were added in pre2) and [MC-253517](https://bugs.mojang.com/browse/MC-253517), `online-mode=false` servers should never be treated as "dangerous", even if their `enforce-secure-profile=true`, because the chat is still considered unsigned despite what is asked from the client. 

Correct me if I'm wrong.

**Comment by Aizistral** [comment]
This should be fixed by 0f05789b045ea73e4eb18c7b2ab7398d72df76b0, since the mod now has some capacity to dynamically detect server demands while logging in. Servers in offline mode will not require you to expose your public key even if `enforce-secure-profile` is enabled, and will not ever relay your key to other players.

However, if you log into offline-mode server without this mod (or some other mod that strips signatures) installed - your client will still send signed messages, and server will still relay them complete with signatures. Other clients will not be able to verify those signatures since server does not give them your public key; however, if those signed messages get reported to Mojang - they will be able to verify them.
