### ISSUE TITLE
Crashes game before entering menu screen

### ISSUE THREAD

**Issue by littlepianist** [Aizistral-Studios/No-Chat-Reports#456]
### Modloader

Forge

### Minecraft Version

1.20.1

### Modloader Version

Forge 47.2.19

### No Chat Reports Version

1.20.1-v2.2.2

### The latest.log File

https://pastebin.com/LNXbVwWT

### Bug Description

Can't load minecraft and crash

### Other Information

The crash happened after I updated embeddium ++ but its owner said the crash is caused by no chat report. https://github.com/SrRapero720/EmbeddiumPlus/issues/14

**Comment by SrRapero720** [comment]
ignore the issue

@littlepianist please consider next time send logs instead of a crash report
you had a missing dependency 
`net.minecraftforge.fml.ModLoadingException: Mod ¡±eembeddiumplus¡±r requires ¡±6textrues_embeddium_options¡±r ¡±oany¡±r
¡±7Currently, ¡±6textrues_embeddium_options¡±r¡±7 is ¡±o¡±nnot installed`

my bad to not request logs in first place

**Comment by littlepianist** [comment]
Oh didn't notice the dependency is needed after the update. Will remember to send logs next time.
