### ISSUE TITLE
Add warning when sending message with signature

### ISSUE THREAD

**Issue by sertonix** [Aizistral-Studios/No-Chat-Reports#81]
With the recent changes there will be a lot of servers that enforce signatures. It would be nice if you have a warning or toggle to not accidentally send a signed message. This would remind you to use a chat alternative of choice.

**Comment by Aizistral** [comment]
You already have a warning in the form of safety status icon. What exactly you suggest beyond it?

**Comment by Aizistral** [comment]
Ah, I guess that icon didn't work for a few versions. You should be able to see it in 1.19.1-pre3-v1.4.2 though, near the bottom right of chat screen.

**Comment by pointydev** [comment]
I know this is a month old necro but may I suggest that while connected to "whitelisted" servers, there be an option to still prevent sending messages clientside, or a prompt per-message option (e.g. doubletap enter with a hotbar prompt). This would allow users to use `whitelistAllServers` while staying relatively protected, as I'm sure the safety status icon, while enabled by default, will be missed due to bad habits and/or forgotten about during gameplay.

**Comment by Aizistral** [comment]
It's more complicated than that, because - how do we define "message"? Do we count commands as messages? If we do not, what do we do about `/say` and `/msg`? If we do, wouldn't it be annoying to go through all those double taps and such for every command? What about custom commands?

I don't want to make raising user awareness more invasive than it currently is. Playing on `enforce-secure-profile` servers is already inherently unsafe, and enabling `whitelistAllServers` option is, by extension, too. NCR is there to help and inform the user, but not to babysit them.
