### ISSUE TITLE
Conflict with Styled Chat mod

### ISSUE THREAD

**Issue by LovelyA72** [Aizistral-Studios/No-Chat-Reports#9]
This mod is currently incompatible with the styled chat mod on 1.19.0 server
https://github.com/Patbox/StyledChat
Logs will be added soon

**Comment by LovelyA72** [comment]
Logs: https://mclo.gs/2XaAeC7
I am guessing #7 will fix this issue but I am not sure.

**Comment by Aizistral** [comment]
Ah well, that's a pain. It will not fix that because StyledChat and my mod try to redirect the same call. Since the feature provided by that specific `@Redirect` is optional anyways, I'll have to make a companion plugin to make its application optional as well, or just mix into `ServerGamePacketListenerImpl` directly instead of doing this redirect.
