### ISSUE TITLE
Client-side chat encryption

### ISSUE THREAD

**Issue by dallytaur** [Aizistral-Studios/No-Chat-Reports#95]
Could do something where you encode a scramble version of the patched player can do code leaving a "this message needs no chat reports mod to read" followed unseen chat message that can be unscramble by the patch.

it allows patched game player to talk to each other safely while also promoting the mod.

**Comment by Aizistral** [comment]
That doesn't make much sense without server's collaboration, because on big servers you will just get muted by local moderators for spam if they want to support chat reporting, and if not - they will have something like NCR on server itself. I leave such thing open for future consideration, but at this point I wish not to integrate anything like this into this particular mod.

**Comment by Madis0** [comment]
Just to keep a log of what we've discussed: this may still be useful for private Realms, as that currently has no reliable way of preventing chat reports. 
Perhaps the Realm owner could add some kind of [color code](https://minecraft.fandom.com/wiki/Formatting_codes#Color_codes) sequence [to the description](https://youtu.be/39Xg189Sc0o?t=290), that would automatically activate the encryption for all clients that have NCR? And the key could be created by some metadata properties of the server.

**Comment by Aizistral** [comment]
In the works, will be available as part of next release.
